version: "3.8"
services:
  jmeter:
    build: .
    image: jmeter-cli:5.6.3
    container_name: jmeter-runner
    entrypoint: ["tail", "-f", "/dev/null"]   # contenedor "idle" esperando comandos
    volumes:
      - ./:/home/jmeter
    restart: unless-stopped